apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-nginx
  name: test-nginx
spec:
  containers:
  - image: nginx:stable
    name: test-nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}